name: Build Linux Kernel for Apple A10

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ARCH: arm64
      CROSS_COMPILE: aarch64-linux-gnu-

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            wget \
            curl \
            git \
            autoconf \
            automake \
            libtool \
            pkg-config \
            zlib1g-dev \
            libncurses5-dev \
            libncursesw5-dev \
            libelf-dev \
            libssl-dev

      - name: Install qemu-user-static from source
        run: |
          git clone https://gitlab.com/qemu-project/qemu.git
          cd qemu
          ./configure --static --target-list=aarch64-linux-user
          make -j$(nproc)
          sudo make install
          cd ..

      - name: Install gcc-aarch64-linux-gnu from source
        run: |
          wget https://ftp.gnu.org/gnu/gcc/gcc-10.2.0/gcc-10.2.0.tar.gz
          tar -xzf gcc-10.2.0.tar.gz
          cd gcc-10.2.0
          ./contrib/download_prerequisites
          mkdir build
          cd build
          ../configure --target=aarch64-linux-gnu --enable-languages=c,c++ --disable-multilib
          make -j$(nproc)
          sudo make install
          cd ../..

      - name: Install bison from source
        run: |
          wget https://ftp.gnu.org/gnu/bison/bison-3.7.6.tar.gz
          tar -xzf bison-3.7.6.tar.gz
          cd bison-3.7.6
          ./configure
          make -j$(nproc)
          sudo make install
          cd ..

      - name: Install flex from source
        run: |
          wget https://github.com/westes/flex/files/735321/flex-2.6.4.tar.gz
          tar -xzf flex-2.6.4.tar.gz
          cd flex-2.6.4
          ./configure
          make -j$(nproc)
          sudo make install
          cd ..

      - name: Install bc from source
        run: |
          wget https://ftp.gnu.org/gnu/bc/bc-1.07.1.tar.gz
          tar -xzf bc-1.07.1.tar.gz
          cd bc-1.07.1
          ./configure
          make -j$(nproc)
          sudo make install
          cd ..

      - name: Download Linux kernel source
        run: git clone --depth 1 --branch v6.1 https://github.com/torvalds/linux.git

      - name: Copy A10 defconfig
        run: |
          cp a10_defconfig linux/arch/arm64/configs/a10_defconfig

      - name: Configure kernel
        run: |
          cd linux
          make ARCH=$ARCH CROSS_COMPILE=$CROSS_COMPILE a10_defconfig
          make ARCH=$ARCH CROSS_COMPILE=$CROSS_COMPILE menuconfig

      - name: Compile kernel
        run: |
          cd linux
          make -j$(nproc) ARCH=$ARCH CROSS_COMPILE=$CROSS_COMPILE

      - name: Upload compiled kernel
        uses: actions/upload-artifact@v3
        with:
          name: linux-kernel
          path: linux/arch/arm64/boot/Image
